const style ={
    container:{
        width:'100%',height:'100%',flexDirection:'row',display:'flex',backgroundColor:'#FBF3E6',
    },
    leftContainer:{
        width:'40%',height:'100%',alignItems:'center',justifyContent:'center',display:'flex',marginTop:20
    },
    rightContainer:{
        width:'60%',height:'100%'
    },
    loginContainer:{
        width:'80%',height:'100%',alignItems:'center',justifyContent:'cemter',display:'flex',flexDirection:'column',borderRadius:25
    },
    loginText:{
        fontSize:25,fontWeight:'bold',marginTop:'15%',marginBottom:'10%'
    },
    inputContainer:{
        display:'flex',flexDirection:'column',width:'65%',marginBottom:'5%'
    },
    inputText:{
        marginBottom:0,alignItems:'flex-start',display:'flex',fontWeight:'500',paddingLeft:2
    },
    inputGroup:{
        width:'100%',marginBottom:0,borderWidth:0
    },
    inputGroupText:{
        backgroundColor:'#F9F9F9',borderLeftWidth:0
    },
    logInButton:{
        width:'60%',height:'8%',marginTop:'3%',backgroundColor:'#D9054F'
    },
    logInFacebook:{
        width:'60%',height:'8%',marginTop:'2%',borderWidth:1.5,flexDirection:'row',display:'flex'
    },
    facebookLogo:{
        marginLeft:10,marginRight:4
    },
    dontHaveAccount:{
        color:'#858585',fontSize:11,marginTop:'5%',backgroundColor:'transparent',borderWidth:0
    },
    createAccountText:{
        fontSize:25,fontWeight:'bold',marginTop:'0%',marginBottom:'3%'
    },
    roleContainer:{
        flexDirection:'row',display:'flex',width:'65%',justifyContent:'space-around',marginBottom:'3%'
    },
    alreadyHaveAccount:{
        color:'#858585',fontSize:11,marginTop:'1%',backgroundColor:'transparent',borderWidth:0
    },
    chefImg:{
        width:'100%',height:'100%'
    }
    
}

export default style;
